export const VI = {
  nav: {
    logo: 'SONi',
    tagline: 'Kính Mắt',
    newArrivals: 'Hàng Mới',
    eyeglasses: 'Gọng Kính',
    sunglasses: 'Kính Râm',
    prescription: 'Kính Cận',
    kids: 'Trẻ Em',
    tryOn: 'Thử 3D',
    search: 'Tìm kiếm kính...',
    cart: 'Giỏ hàng',
    contact: 'Liên hệ',
    menu: 'Menu',
    close: 'Đóng',
  },

  home: {
    heroHeading1: 'Kính Đẹp',
    heroHeading2: 'Đúng Mốt',
    heroHeading3: 'Nét Như SONi',
    heroSub: 'Thử kính ảo ngay trên khuôn mặt bạn — không cần ra cửa hàng.',
    heroCTA: 'Thử Kính Ngay',
    heroCTA2: 'Xem Bộ Sưu Tập',
    categoriesHeading: 'Khám Phá Theo Kiểu Dáng',
    featuredHeading: 'Bán Chạy Nhất',
    featuredSub: 'Được khách hàng yêu thích nhất tháng này',
    promoHeading: 'Thử Kính Tại Nhà',
    promoSub: 'Công nghệ AR tiên tiến giúp bạn thấy mình trông như thế nào trước khi mua. Hoàn toàn miễn phí.',
    promoCTA: 'Thử Ngay Miễn Phí',
    newArrivalsHeading: 'Hàng Mới Về',
    viewAll: 'Xem Tất Cả',
    promoStrip: 'ĐẶT HÀNG NGAY – GIẢM THÊM 20% – ÁP DỤNG TẤT CẢ SẢN PHẨM',
  },

  categories: {
    fullRim: 'Full Rim',
    rimless: 'Không Viền',
    semiRimless: 'Nửa Viền',
    round: 'Mắt Tròn',
    square: 'Mắt Vuông',
    rectangle: 'Chữ Nhật',
    catEye: 'Mắt Mèo',
    aviator: 'Phi Công',
    oval: 'Oval',
    geometric: 'Đa Giác',
  },

  catalog: {
    title: 'Gọng Kính',
    allFrames: 'Tất Cả Gọng',
    viewFrames: 'Xem Gọng',
    viewARTryOn: 'Thử 3D',
    filterTitle: 'Bộ Lọc',
    filterToggle: 'Lọc',
    resetFilters: 'Xóa bộ lọc',
    sortBy: 'Sắp xếp',
    sortOptions: {
      'ban-chay': 'Bán chạy nhất',
      'gia-tang': 'Giá tăng dần',
      'gia-giam': 'Giá giảm dần',
      'moi-nhat': 'Mới nhất',
    } as Record<string, string>,
    showingResults: (count: number, total: number) =>
      `Hiển thị ${count} / ${total} sản phẩm`,
    noResults: 'Không tìm thấy sản phẩm phù hợp',
    noResultsSub: 'Hãy thử thay đổi bộ lọc để xem thêm sản phẩm.',
    filterSections: {
      frameType: 'Loại Gọng',
      frameShape: 'Hình Dáng',
      color: 'Màu Sắc',
      material: 'Chất Liệu',
      gender: 'Giới Tính',
      price: 'Mức Giá',
      brand: 'Thương Hiệu',
    },
    frameTypes: {
      'full-rim': 'Full Viền',
      'rimless': 'Không Viền',
      'semi-rimless': 'Nửa Viền',
    } as Record<string, string>,
    frameShapes: {
      round: 'Mắt Tròn',
      square: 'Mắt Vuông',
      rectangle: 'Chữ Nhật',
      'cat-eye': 'Mắt Mèo',
      aviator: 'Phi Công',
      oval: 'Oval',
      geometric: 'Đa Giác',
    } as Record<string, string>,
    materials: {
      metal: 'Kim Loại',
      plastic: 'Nhựa',
      titanium: 'Titanium',
      combination: 'Kết Hợp',
    } as Record<string, string>,
    genders: {
      nam: 'Nam',
      nu: 'Nữ',
      unisex: 'Unisex',
    } as Record<string, string>,
  },

  productCard: {
    buyOnZalo: 'Đặt Hàng Ngay',
    addToWishlist: 'Yêu thích',
    sizeLabel: (size: string) => `Kích cỡ: ${size}`,
    bestSeller: 'Bán Chạy',
    newArrival: 'Hàng Mới',
    outOfStock: 'Hết Hàng',
    reviewCount: (n: number) => `(${n.toLocaleString('vi-VN')})`,
    viewDetail: 'Xem Chi Tiết',
  },

  product: {
    buyNow: 'Đặt Hàng Ngay',
    discount: 'Giảm 20%',
    tryOnAR: 'AI Tư Vấn Gọng Kính Phù Hợp',
    addToWishlist: 'Thêm vào yêu thích',
    lensSelectTitle: 'Chọn Loại Tròng',
    lensSelectSub: 'Thêm tròng kính phù hợp nhu cầu của bạn',
    frameOnly: 'Chỉ Gọng Kính',
    totalPrice: 'Tổng Cộng',
    specsTitle: 'Thông Số Kỹ Thuật',
    specLabels: {
      frameType: 'Loại Gọng',
      material: 'Chất Liệu',
      shape: 'Hình Dáng',
      bridgeWidth: 'Cầu Mũi',
      lensWidth: 'Rộng Mắt Kính',
      templeLength: 'Dài Gọng',
      weight: 'Trọng Lượng',
      gender: 'Giới Tính',
      frameWidth: 'Kích Cỡ',
    },
    colorTitle: 'Màu Sắc',
    relatedTitle: 'Có Thể Bạn Sẽ Thích',
    zaloCTAHint: 'Đặt hàng ngay — nhận tư vấn miễn phí từ SONi Kính',
    recommended: 'Được Đề Xuất',
    addLens: '+ Thêm Tròng',
    frameOnlyLabel: 'Chỉ Gọng',
    inStock: 'Còn hàng',
    outOfStock: 'Hết hàng',
    brand: 'Thương hiệu',
    sku: 'Mã sản phẩm',
    shareProduct: 'Chia sẻ sản phẩm',
    breadcrumb: {
      home: 'Trang Chủ',
      catalog: 'Gọng Kính',
    },
  },

  lens: {
    frameOnly: {
      name: 'Chỉ Gọng',
      description: 'Mua gọng kính không kèm tròng',
      features: [],
    },
    basic: {
      name: 'Tròng Cơ Bản',
      description: 'Tròng nhựa CR-39 trong suốt, chống UV400, phủ chống trầy',
      features: ['Chống UV400', 'Phủ chống trầy', 'Chỉ số 1.56', 'Phù hợp 0–4 độ'],
    },
    blueLight: {
      name: 'Chống Ánh Sáng Xanh',
      description: 'Bảo vệ mắt khi dùng máy tính, điện thoại nhiều giờ',
      features: ['Lọc ánh sáng xanh HEV', 'Chống UV400', 'Giảm mỏi mắt', 'Phủ chống trầy'],
    },
    photochromic: {
      name: 'Tự Đổi Màu',
      description: 'Trong suốt trong nhà, tự động tối khi ra ngoài trời nắng',
      features: ['Đổi màu trong 30 giây', 'Chống UV400', 'Bảo vệ 100% tia UV'],
    },
    progressive: {
      name: 'Đa Tròng',
      description: 'Dành cho người cần kính nhìn gần và xa đồng thời',
      features: ['Nhìn gần + trung + xa', 'Không đường phân cách', 'Cần thời gian thích nghi'],
    },
  },

  ar: {
    title: 'Thử Kính Ảo',
    subtitle: 'Xem bạn trông thế nào với từng gọng kính',
    permissionTitle: 'Cho Phép Truy Cập Camera',
    permissionDesc: 'SONi Kính cần quyền truy cập camera để hiển thị kính lên khuôn mặt bạn. Chúng tôi không lưu trữ bất kỳ hình ảnh nào.',
    allowCamera: 'Cho Phép Camera',
    deniedTitle: 'Không Có Quyền Truy Cập Camera',
    deniedDesc: 'Bạn đã từ chối quyền truy cập camera. Vui lòng vào cài đặt trình duyệt để cho phép.',
    errorTitle: 'Thiết Bị Không Hỗ Trợ Camera',
    errorDesc: 'Xem ảnh sản phẩm hoặc liên hệ Zalo để được tư vấn trực tiếp.',
    detecting: 'Đang nhận diện khuôn mặt...',
    faceNotFound: 'Không thấy khuôn mặt — hãy đảm bảo đủ ánh sáng',
    selectGlasses: 'Chọn gọng kính muốn thử',
    currentlyTrying: 'Đang thử:',
    orderThisFrame: 'Đặt Hàng Gọng Này',
    switchCamera: 'Đổi Camera',
    stopTryOn: 'Thoát',
    contactZalo: 'Liên Hệ Zalo',
    loadingModel: 'Đang tải mô hình AI...',
    loadingCamera: 'Đang kết nối camera...',
  },

  zalo: {
    floatingLabel: 'Tư vấn Zalo',
    toastMessage: 'Nội dung đã được sao chép — hãy dán vào Zalo để đặt hàng!',
    defaultMessage: 'Xin chào SONi Kính! Tôi muốn được tư vấn về kính mắt.',
    orderMessage: (productName: string, color: string, lens: string, id: string) =>
      `Xin chào SONi Kính! Tôi muốn đặt hàng:\n- Gọng: ${productName}\n- Màu: ${color}\n- Tròng: ${lens}\n- Mã SP: ${id}\nVui lòng tư vấn thêm ạ.`,
  },

  common: {
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra',
    retry: 'Thử lại',
    close: 'Đóng',
    seeMore: 'Xem thêm',
    seeLess: 'Thu gọn',
    vnd: (price: number) =>
      new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price),
    free: 'Miễn phí',
    from: 'Từ',
    back: 'Quay lại',
    home: 'Trang chủ',
    mm: (n: number) => `${n}mm`,
    grams: (n: number) => `${n}g`,
    addPrice: (n: number) =>
      n === 0 ? 'Miễn phí' : `+${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(n)}`,
  },
} as const
